### ISSUE TITLE
Message Modelling

### ISSUE THREAD

**Issue by bastie87** [ComplexAvionicsSystems/OAAM#2]
Hi,
I'd like to have the opportunity to specify a MessageType for a ConnectionType.

ConnectionType should have an attribute that may refer to a message type. With this information I can distinguish between buses / complex transmission (e.g., CAN, A664, A429) and direct / simple transmission (e.g., discrete, analogue)

MessageType Attribute "Alignment" is misspelled. (double L instead of single L)

Messages should have an attribute Type so that I can reference Message to a type.
Messages should have attributes to define startingPoints (sources) and endPoints (destinations)

BR
Bastian

**Comment by bastie87** [comment]
+ MessageType Attribute "Alignment" is misspelled. (double L instead of single L)

**Comment by annighoefer** [comment]
Thank you for solving this issue yourself. I merged the changes in the main repository. Some icons where overwritten, but I recovered them from an older commit.
